# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "service"
version = "1.34.1"
authors= {workspace = true}
edition= {workspace = true}
exclude = ["tests/testdata/npm/registry/*"]
license= {workspace = true}
repository= {workspace = true}
description = "Provides the deno executable"

[build-dependencies]
deno_runtime = { workspace = true, features = ["snapshot_from_snapshot", "include_js_files_for_snapshotting"] }
deno_core = { workspace = true, features = ["include_js_files_for_snapshotting"] }
lazy-regex= {workspace = true}
serde= {workspace = true}
serde_json= {workspace = true}
zstd= {workspace = true}
glibc_version = "0.1.2"

[target.'cfg(windows)'.build-dependencies]
winapi= {workspace = true}
winres= {workspace = true}

[dependencies]
deno_ast = { workspace = true, features = ["bundler", "cjs", "codegen", "dep_graph", "module_specifier", "proposal", "react", "sourcemap", "transforms", "typescript", "view", "visit"] }
deno_core = { workspace = true, features = ["include_js_files_for_snapshotting"] }
deno_doc = "0.62.0"
deno_emit = "0.20.0"
deno_graph = "=0.48.1"
deno_lint = { version = "0.45.0", features = ["docs"] }
deno_npm= {workspace = true}
deno_runtime = { workspace = true, features = ["dont_create_runtime_snapshot", "include_js_files_for_snapshotting"] }
deno_semver= {workspace = true}
deno_task_shell = "0.12.0"
napi_sym= {workspace = true}
deno_lockfile= {workspace = true}

context ={path="../context"}
async-channel = {workspace = true}
async-trait= {workspace = true}
atty= {workspace = true}
base32 = "=0.4.0"
base64= {workspace = true}
cache_control= {workspace = true}
chrono = { version = "=0.4.22", default-features = false, features = ["std"] }
clap = { version = "=4.1.10", features = ["string"] }
clap_complete = "=4.1.5"
clap_complete_fig = "=4.1.2"
console_static_text= {workspace = true}
data-url= {workspace = true}
dissimilar = "=1.0.4"
dprint-plugin-json = "=0.17.2"
dprint-plugin-markdown = "=0.15.2"
dprint-plugin-typescript = "=0.84.4"
encoding_rs= {workspace = true}
env_logger = "=0.9.0"
eszip = "=0.41.0"
fancy-regex = "=0.10.0"
fastwebsockets= {workspace = true}
flate2= {workspace = true}
fs3= {workspace = true}
glob = "0.3.1"
http= {workspace = true}
hyper= {workspace = true,features = ["full"] }
import_map = "=0.15.0"
indexmap= {workspace = true}
jsonc-parser = { version = "=0.21.1", features = ["serde"] }
lazy-regex= {workspace = true}
libc= {workspace = true}
log = { workspace = true, features = ["serde"] }
lsp-types= {workspace = true}
monch = "=0.4.2"
notify= {workspace = true}
once_cell= {workspace = true}
os_pipe= {workspace = true}
percent-encoding= {workspace = true}
pin-project= {workspace = true}
rand = { workspace = true, features = ["small_rng"] }
regex= {workspace = true}
ring= {workspace = true}
rustyline = { version = "=10.0.0", default-features = false, features = ["custom-bindings"] }
rustyline-derive = "=0.7.0"
serde= {workspace = true}
serde_repr= {workspace = true}
shell-escape = "=0.1.5"
tar= {workspace = true}
tempfile= {workspace = true}
text-size = "=1.1.0"
text_lines = "=0.6.0"
thiserror= {workspace = true}
tokio= {workspace = true}
tokio-util= {workspace = true}
tower-lsp= {workspace = true}
bytes = {workspace = true}
twox-hash = "=1.6.3"
typed-arena = "=2.0.1"
uuid = { workspace = true, features = ["serde"] }
walkdir = "=2.3.2"
zstd= {workspace = true}
tower ={ version = "0.4", features = ["make"] }
crossbeam ={version="0.8",features=["std"]}
lazy_static = "1.4.0"
[target.'cfg(windows)'.dependencies]
fwdansi= {workspace = true}
junction = "=0.2.0"
winapi = { workspace = true, features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }

[target.'cfg(unix)'.dependencies]
nix= {workspace = true}

[dev-dependencies]
dotenv = "=0.15.0"
flaky_test = "=0.1.0"
once_cell= {workspace = true}
os_pipe= {workspace = true}
trust-dns-client = "=0.22.0"
trust-dns-server = "=0.22.0"

