# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_http"
version = "0.102.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "HTTP server implementation for Deno"

[features]
"__zombie_http_tracking" = []
"__http_tracing" = []

[lib]
path = "lib.rs"

[[bench]]
name = "compressible"
harness = false

[dependencies]
async-compression = { version = "0.3.12", features = ["tokio", "brotli", "gzip"] }
async-trait.workspace = true
base64.workspace = true
brotli = "3.3.4"
bytes.workspace = true
cache_control.workspace = true
deno_core.workspace = true
deno_net.workspace = true
deno_websocket.workspace = true
flate2.workspace = true
fly-accept-encoding = "0.2.0"
http.workspace = true
httparse.workspace = true
hyper = { workspace = true, features = ["server", "stream", "http1", "http2", "runtime"] }
hyper1 = { package = "hyper", features = ["full"], version = "1.0.0-rc.3" }
memmem.workspace = true
mime = "0.3.16"
once_cell.workspace = true
percent-encoding.workspace = true
phf = { version = "0.10", features = ["macros"] }
pin-project.workspace = true
ring.workspace = true
serde.workspace = true
slab.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["io"] }

[dev-dependencies]
bencher.workspace = true
rand.workspace = true
